/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Admin
 */
public class Start extends javax.swing.JPanel {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(960, 540));
        setMinimumSize(new java.awt.Dimension(960, 540));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(960, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newButton.setBackground(new java.awt.Color(255, 255, 255));
        newButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        newButton.setForeground(new java.awt.Color(31, 31, 31));
        newButton.setText("Nueva cola");
        add(newButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 160, 50));

        loadButton.setBackground(new java.awt.Color(255, 255, 255));
        loadButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        loadButton.setForeground(new java.awt.Color(31, 31, 31));
        loadButton.setText("Cargar cola");
        add(loadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/psicon.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pstext.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg.png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));
    }// </editor-fold>//GEN-END:initComponents
    
    public javax.swing.JButton getNewButton() {
        return newButton;
    }
    
    public javax.swing.JButton getLoadButton() {
        return loadButton;
    }

    private java.awt.Image bgImg;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton newButton;
    // End of variables declaration//GEN-END:variables
}
